-- Tabla de productos
CREATE TABLE tbl_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  image TEXT,
  category TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO tbl_products (name, price, image, category) VALUES
('Café Caramel con Chocolate', 59.9, 'https://devsapihub.com/img-fast-food/cafe_01.jpg', 'cafe'),
('Café Frio con Chocolate Grande', 49.9, 'https://devsapihub.com/img-fast-food/cafe_02.jpg', 'cafe'),
('Latte Frio con Chocolate Grande', 54.9, 'https://devsapihub.com/img-fast-food/cafe_03.jpg', 'cafe'),
('Latte Frio con Chocolate Grande', 54.9, 'https://devsapihub.com/img-fast-food/cafe_04.jpg', 'cafe'),
('Malteada Fria con Chocolate Grande', 54.9, 'https://devsapihub.com/img-fast-food/cafe_05.jpg', 'cafe'),
('Café Mocha Caliente Chico', 39.9, 'https://devsapihub.com/img-fast-food/cafe_06.jpg', 'cafe'),
('Café Mocha Caliente Grande con Chocolate', 59.9, 'https://devsapihub.com/img-fast-food/cafe_07.jpg', 'cafe'),
('Café Caliente Capuchino Grande', 59.9, 'https://devsapihub.com/img-fast-food/cafe_08.jpg', 'cafe'),
('Café Mocha Caliente Mediano', 49.9, 'https://devsapihub.com/img-fast-food/cafe_09.jpg', 'cafe'),
('Café Mocha Frio con Caramelo Mediano', 49.9, 'https://devsapihub.com/img-fast-food/cafe_10.jpg', 'cafe'),
('Café Mocha Frio con Chocolate Mediano', 49.9, 'https://devsapihub.com/img-fast-food/cafe_11.jpg', 'cafe'),
('Café Espresso', 29.9, 'https://devsapihub.com/img-fast-food/cafe_12.jpg', 'cafe'),
('Café Capuchino Grande con Caramelo', 59.9, 'https://devsapihub.com/img-fast-food/cafe_13.jpg', 'cafe'),
('Café Caramelo Grande', 59.9, 'https://devsapihub.com/img-fast-food/cafe_14.jpg', 'cafe'),
('Paquete de 3 donas de Chocolate', 39.9, 'https://devsapihub.com/img-fast-food/donas_01.jpg', 'dona'),
('Paquete de 3 donas Glaseadas', 39.9, 'https://devsapihub.com/img-fast-food/donas_02.jpg', 'dona'),
('Dona de Fresa', 19.9, 'https://devsapihub.com/img-fast-food/donas_03.jpg', 'dona'),
('Dona con Galleta de Chocolate', 19.9, 'https://devsapihub.com/img-fast-food/donas_04.jpg', 'dona'),
('Dona glass con Chispas Sabor Fresa', 19.9, 'https://devsapihub.com/img-fast-food/donas_05.jpg', 'dona'),
('Dona glass con Chocolate', 19.9, 'https://devsapihub.com/img-fast-food/donas_06.jpg', 'dona'),
('Dona de Chocolate con MÁS Chocolate', 19.9, 'https://devsapihub.com/img-fast-food/donas_07.jpg', 'dona'),
('Paquete de 3 donas de Chocolate', 39.9, 'https://devsapihub.com/img-fast-food/donas_08.jpg', 'dona'),
('Paquete de 3 donas con Vainilla y Chocolate', 39.9, 'https://devsapihub.com/img-fast-food/donas_09.jpg', 'dona'),
('Paquete de 6 Donas', 69.9, 'https://devsapihub.com/img-fast-food/donas_10.jpg', 'dona'),
('Paquete de 3 Variadas', 39.9, 'https://devsapihub.com/img-fast-food/donas_11.jpg', 'dona'),
('Dona Natural con Chocolate', 19.9, 'https://devsapihub.com/img-fast-food/donas_12.jpg', 'dona'),
('Paquete de 3 Donas de Chocolate con Chispas', 39.9, 'https://devsapihub.com/img-fast-food/donas_13.jpg', 'dona'),
('Dona Chocolate y Coco', 19.9, 'https://devsapihub.com/img-fast-food/donas_14.jpg', 'dona'),
('Paquete Galletas de Chocolate', 29.9, 'https://devsapihub.com/img-fast-food/galletas_01.jpg', 'galletas'),
('Paquete Galletas de Chocolate y Avena', 39.9, 'https://devsapihub.com/img-fast-food/galletas_02.jpg', 'galletas'),
('Paquete de Muffins de Vainilla', 39.9, 'https://devsapihub.com/img-fast-food/galletas_03.jpg', 'galletas'),
('Paquete de 4 Galletas de Avena', 24.9, 'https://devsapihub.com/img-fast-food/galletas_04.jpg', 'galletas'),
('Galletas de Mantequilla Variadas', 39.9, 'https://devsapihub.com/img-fast-food/galletas_05.jpg', 'galletas'),
('Galletas de sabores frutales', 39.9, 'https://devsapihub.com/img-fast-food/galletas_06.jpg', 'galletas'),
('Hamburguesa Sencilla', 59.9, 'https://devsapihub.com/img-fast-food/hamburguesas_01.jpg', 'hamburguesa'),
('Hamburguesa de Pollo', 59.9, 'https://devsapihub.com/img-fast-food/hamburguesas_02.jpg', 'hamburguesa'),
('Hamburguesa de Pollo y Chili', 59.9, 'https://devsapihub.com/img-fast-food/hamburguesas_03.jpg', 'hamburguesa'),
('Hamburguesa Queso y  Pepinos', 59.9, 'https://devsapihub.com/img-fast-food/hamburguesas_04.jpg', 'hamburguesa'),
('Hamburguesa Cuarto de Libra', 59.9, 'https://devsapihub.com/img-fast-food/hamburguesas_05.jpg', 'hamburguesa'),
('Hamburguesa Doble Queso', 69.9, 'https://devsapihub.com/img-fast-food/hamburguesas_06.jpg', 'hamburguesa'),
('Hot Dog Especial', 49.9, 'https://devsapihub.com/img-fast-food/hamburguesas_07.jpg', 'hamburguesa'),
('Paquete 2 Hot Dogs', 69.9, 'https://devsapihub.com/img-fast-food/hamburguesas_08.jpg', 'hamburguesa'),
('4 Rebanadas de Pay de Queso', 69.9, 'https://devsapihub.com/img-fast-food/pastel_01.jpg', 'pastel'),
('Waffle Especial', 49.9, 'https://devsapihub.com/img-fast-food/pastel_02.jpg', 'pastel'),
('Croissants De la casa.jpg', 39.9, 'https://devsapihub.com/img-fast-food/pastel_03.jpg', 'pastel'),
('Pay de Queso', 19.9, 'https://devsapihub.com/img-fast-food/pastel_04.jpg', 'pastel'),
('Pastel de Chocolate', 29.9, 'https://devsapihub.com/img-fast-food/pastel_05.jpg', 'pastel'),
('Rebanada Pastel de Chocolate', 29.9, 'https://devsapihub.com/img-fast-food/pastel_06.jpg', 'pastel'),
('Pizza Spicy con Doble Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_01.jpg', 'pizza'),
('Pizza Jamón y Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_02.jpg', 'pizza'),
('Pizza Doble Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_03.jpg', 'pizza'),
('Pizza Especial de la Casa', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_04.jpg', 'pizza'),
('Pizza Chorizo', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_05.jpg', 'pizza'),
('Pizza Hawaiana', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_06.jpg', 'pizza'),
('Pizza Tocino', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_07.jpg', 'pizza'),
('Pizza Vegetales y Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_08.jpg', 'pizza'),
('Pizza Pepperoni y Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_09.jpg', 'pizza'),
('Pizza Aceitunas y Queso', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_10.jpg', 'pizza'),
('Pizza Queso, Jamón y Champiñones', 69.9, 'https://devsapihub.com/img-fast-food/pizzas_11.jpg', 'pizza');


-- Tabla del carrito
CREATE TABLE tbl_cart_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  amount INTEGER NOT NULL CHECK (amount > 0),
  product_id UUID REFERENCES tbl_products(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW()
);
